server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(98Uh4mwteotm41+cbOPTDBOBPMv8IcvO0rhkWvoaAgn5hxYtiFNFFg4KIX9pzb5fRHPKB45btJ67+7jfGhYx7Z8jbCv/xqCniSDyWIweoe2ySkIXFacBhPTpF2GU92QzuFGoAVYTQ0yuY7XtXMnDDM0779y+1W6Dv06cQOiVxyx4IWFonqfM4zJ879gMrVncXqSlcy59UaeTjyGGO+aFUA==)
    username: ENC(KAM51FRmp61vPzCgS5f5vYGcsk7Y1rd+9rnyJqN6OMh3f2yqhaqqWzcIRuwbKy4q)
    password: ENC(viwiDApGQQrWf1E6N9xMKfYR4z7cTEyOiTGh4lXfv1nJyh1yrDUctOgvsAPFF1pF)
  redis: # redis 配置
    host: 127.0.0.1 # IP
    port: 6379 # 端口
    password: ENC(viwiDApGQQrWf1E6N9xMKfYR4z7cTEyOiTGh4lXfv1nJyh1yrDUctOgvsAPFF1pF) # 密码
    timeout: 10s # 连接超时时间
    lettuce: # lettuce redis 客户端配置
      pool: # 连接池配置
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: 200s # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

avatarImagesFilePath: ${user.dir}${file.separator}UserAvatar${file.separator}
musicImagesFilePath: ${user.dir}${file.separator}MusicPicture${file.separator}
audioFilePath: ${user.dir}${file.separator}Audio${file.separator}
lyricFilePath: ${user.dir}${file.separator}Lyric${file.separator}
mvImagesFilePath: ${user.dir}${file.separator}MVPicture${file.separator}
mvFilePath: ${user.dir}${file.separator}MV${file.separator}
listImagesFilePath: ${user.dir}${file.separator}ListPicture${file.separator}
androidApplicationFilePath: ${user.dir}${file.separator}AndroidApplication${file.separator}
androidApplicationImagesFilePath: ${user.dir}${file.separator}AndroidApplicationPicture${file.separator}
