server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(98Uh4mwteotm41+cbOPTDBOBPMv8IcvO0rhkWvoaAgn5hxYtiFNFFg4KIX9pzb5fRHPKB45btJ67+7jfGhYx7Z8jbCv/xqCniSDyWIweoe2ySkIXFacBhPTpF2GU92QzuFGoAVYTQ0yuY7XtXMnDDM0779y+1W6Dv06cQOiVxyx4IWFonqfM4zJ879gMrVncXqSlcy59UaeTjyGGO+aFUA==)
    username: ENC(KAM51FRmp61vPzCgS5f5vYGcsk7Y1rd+9rnyJqN6OMh3f2yqhaqqWzcIRuwbKy4q)
    password: ENC(viwiDApGQQrWf1E6N9xMKfYR4z7cTEyOiTGh4lXfv1nJyh1yrDUctOgvsAPFF1pF)
  redis: # redis 配置
    host: 127.0.0.1 # IP
    port: 6379 # 端口
    password: 13879640liu # 密码
    timeout: 10s # 连接超时时间
    lettuce: # lettuce redis 客户端配置
      pool: # 连接池配置
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: 200s # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

avatarImagesFilePath: F:\Projects\Android\GraduationProject\UserAvatar\
musicImagesFilePath: F:\Projects\Android\GraduationProject\MusicPicture\
audioFilePath: F:\Projects\Android\GraduationProject\Audio\
lyricFilePath: F:\Projects\Android\GraduationProject\Lyric\